version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: huhysitedb
      POSTGRES_USER: amol
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OWNERS=131445541
      - TELEGRAM_ADMIN_IDS=131445541
      - TGBOT_TOKEN=7350767988:AAGt0-dMsehLYl3gXFXokjZgQF5JPsqg874
      - ip=localhost
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=mental-veradis-stark-industries-jarvis-4cfc6016.koyeb.app
    volumes:
      - .:/app
      - ./huhysite_my_git/static:/app/static
    depends_on:
      - db

volumes:
  postgres_data:
