# Generated by Django 5.1.6 on 2025-03-06 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва тегу')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount_active',
            field=models.BooleanField(default=False, verbose_name='Активна знижка'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Відсоток знижки'),
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_price', models.BooleanField(default=True, verbose_name='Автооновлення ціни')),
                ('components', models.ManyToManyField(related_name='included_in_packs', to='shop.product', verbose_name='Компоненти паку')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pack_details', to='shop.product', verbose_name='Товар-пак')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.tag', verbose_name='Теги'),
        ),
    ]
