# Generated by Django 5.1.1 on 2025-01-28 18:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_postcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
