# Generated by Django 5.1.6 on 2025-09-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
